### ISSUE TITLE
popover position

### ISSUE THREAD

**Issue by coder4567** [lupidan/PopoverView#2]
hey, previous issue solved, thank you for your hint, 

I have a new problem, I'm using the popover to pop after a selection on a webview is made. When I load the html on the webview I scroll through it horizontally, when the pop over is used to pop on the first page there's no problem and the popover position is exactly where I clicked, but the problem is that when I scroll to another, the popover still pops on the first page of the webview. 
would you kindly look into it and let me know what I'm doing wrong.
Thank u.

**Comment by lupidan** [comment]
I don't know about your code. I don't know where you are adding the PopoverView, or the values you are passing to showPopover...
What I can try to guess, based on the previous question, is that you are not taking into consideration the scroll offset of the Webview. That's all I can think off.
Please, debug your code, check what values you are passing to the showPopover method, and try to gather some conclusions.

**Comment by coder4567** [comment]
here's what I did:
ViewGroup vgr = (ViewGroup) this.getParent();
so the viewGroup isn't the webview anymore but its parents, now it working fine, 
By the way I tried before to add to the Rect the width of the webview times the number of pages but with no success it stayed on the first page, anyway thank you very much,
