### ISSUE TITLE
change frame popoverView

### ISSUE THREAD

**Issue by mustafaerturk** [lupidan/PopoverView#5]
is that possible change the frame of popoverView ?

**Comment by lupidan** [comment]
You can set the popover size to stretch or to a certain size:

For example, to put the size 320x340 points:

```
popoverView.setContentSizeForViewInPopover(new Point(320, 340));
popoverView.showPopoverFromRectInViewGroup(rootView, PopoverView.getFrameForView(v), PopoverView.PopoverArrowDirectionAny, true);
```

**Comment by mustafaerturk** [comment]
Sorry , I ask wrong question .I need to change the border of popOver. You can see the iPad version on the below.

I have to make this 
![aramasonuc](https://f.cloud.github.com/assets/3913742/1291814/7e32343a-3049-11e3-8b60-2c75ee07cd55.jpg)

but ı got this 
![screenshot_2013-10-08-21-42-52](https://f.cloud.github.com/assets/3913742/1291823/af3c6f3c-3049-11e3-81f7-be4936d4eb64.png)

How can i make something like this.

**Comment by lupidan** [comment]
You just need to correctly edit the black borders in your 9 patch image for the box. The left and top border describe what area is resized. The right and bottom borders describe where the content is placed. Please take a reading to this article explaining how the 9patch images work in Android.

http://radleymarx.com/blog/simple-guide-to-9-patch/
